name: Payment service workflow

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

concurrency:
  # Grouped by ref (branch/tag name) not to cancel other jobs running for other feature branches
  group: go_service_${{ github.ref }}
  # > cancel any currently running job or workflow in the same concurrency group
  # in case of multiple pushes to the same branch, we just need the latest, so cancel all previous
  cancel-in-progress: true

env:
  service_name: payment-service
  service_account: "payment-service@flink-core-shared.iam.gserviceaccount.com"

jobs:
   build-kotlin-service:
     name: Build Kotlin service
     runs-on: ubuntu-latest

     steps:
       - name: Checkout
         uses: actions/checkout@v3

       - name: Setup SSH agent for retrieving (private) Github dependencies
         uses: webfactory/ssh-agent@v0.8.0
         with:
           ssh-private-key: ${{ secrets.GOFLINK_CI_SSH_PRIVATE_KEY }}

       - name: Force access to Github repositories using SSH
         run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
           architecture: x64

       - name: Restore Maven cache
         uses: skjolber/maven-cache-github-action@v2.0
         with:
           step: restore

       - uses: DataDog/agent-github-action@v1.3.1
         with:
           api_key: ${{ secrets.DD_TESTS_API_KEY }}
           datadog_site: ${{ secrets.DD_SITE }}
           extra_env: DD_CIVISIBILITY_AGENTLESS_ENABLED=${{ secrets.DD_CIVISIBILITY_AGENTLESS_ENABLED }}

       - name: Build with Maven
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
          DD_ENV=ci ./mvnw --batch-mode --update-snapshots package -Pdd-civisibility sonar:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=goflink \
          -Dsonar.projectKey=goflink_payment-service \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml
          mkdir quarkus-app && cp -r target/quarkus-app/* quarkus-app

       - name: Save Maven cache
         uses: skjolber/maven-cache-github-action@v2.0
         with:
           step: save

       - name: Preserve build archive
         uses: actions/upload-artifact@v3
         with:
           name: quarkus-app
           path: quarkus-app

   build-push-docker-image:
     name: Build and push docker image
     needs: build-kotlin-service
     runs-on: ubuntu-latest

     permissions:
       contents: write # for checkout
       id-token: write # for authenticating to Google Cloud Platform

     steps:
       - name: Checkout
         uses: actions/checkout@v3

       - name: Create target/quarkus-app folder
         run: |
           mkdir -p target/quarkus-app

       - name: Restore build archive
         uses: actions/download-artifact@v3
         with:
           name: quarkus-app
           path: target/quarkus-app

       - uses: goflink/github-actions/build-push-image@v2
         with:
           app_name: ${{ env.service_name }}
           build_dockerfile: src/main/docker/Dockerfile.jvm
