name: Trigger Prod deployment in infra repo

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Image tag which should be deployed

env:
  image_repository_reference: "europe-west3-docker.pkg.dev/flink-core-shared/payment-service/payment-service"
  service_account: "payment-service@flink-core-shared.iam.gserviceaccount.com"

concurrency:
  group: deploy-prod-infra
  cancel-in-progress: false

jobs:
  # used because of GitHub actions issue reported here: https://github.com/actions/runner/issues/480
  # solution proposed here: https://github.com/actions/runner/issues/480#issuecomment-1055373623
  params:
    name: Make environment variables available to the rest of the workflow
    runs-on: ubuntu-latest
    outputs:
      params: ${{ steps.env-vars.outputs.params }}
    steps:
      - id: env-vars
        name: Output environment variables
        run: |
          out=$(cat <<'END_HEREDOC'
          {
            service_account: env.service_account,
            image_repository_reference: env.image_repository_reference
          }
          END_HEREDOC
          )
          params=$(jq -n "${out}" -c -M)
          echo "[DEBUG] params output: ${params}"

          echo "params=${params}" >> $GITHUB_OUTPUT

  update-image-tag:
    runs-on: ubuntu-latest
    name: Update Image Tag
    needs:
      - params
    permissions:
      id-token: write
      contents: write # This is required for actions/checkout@v3

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/592763168884/locations/global/workloadIdentityPools/goflink-github-actions/providers/github-actions
          service_account: ${{ fromJson(needs.params.outputs.params).service_account }}

      - name: Log gcloud configuration
        run: |-
          gcloud info

      - id: get-gke-credentials
        name: get GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          project_id: flink-core-shared
          location: europe-west3
          cluster_name: k8s-main-shared

      - name: Trigger workload deployment
        uses: goflink/github-actions/trigger-workload-deployment@v1
        with:
          gcp_access_token: ${{ steps.auth.outputs.access_token }}
          environment: prod
          image_tag: ${{ github.event.inputs.tag }}
          image_url: ${{ fromJson(needs.params.outputs.params).image_repository_reference }}
          tag_path: ".workload.image.tag"
