name: Trigger Staging deployment in infra repo

on:
  issue_comment:
    types:
      - created
    pull_request:
      branches:
        - main
  workflow_dispatch:
    inputs:
      tag:
        required: false
        description: Image tag which should be deployed

env:
  image_repository_reference: "europe-west3-docker.pkg.dev/flink-core-shared/payment-service/payment-service"
  service_account: "payment-service@flink-core-shared.iam.gserviceaccount.com"

concurrency:
  group: deploy-staging-infra
  cancel-in-progress: false

jobs:
  params:
    name: Make environment variables available to the rest of the workflow
    runs-on: ubuntu-latest
    outputs:
      params: ${{ steps.env-vars.outputs.params }}
    steps:
      - id: env-vars
        name: Output environment variables
        run: |
          out=$(cat <<'END_HEREDOC'
          {
            service_account: env.service_account,
            image_repository_reference: env.image_repository_reference
          }
          END_HEREDOC
          )
          params=$(jq -n "${out}" -c -M)
          echo "[DEBUG] params output: ${params}"

          echo "params=${params}" >> $GITHUB_OUTPUT

  update-image-tag:
    runs-on: ubuntu-latest
    name: Update Image Tag
    needs:
      - params
    if: github.event_name == 'workflow_dispatch' || (github.event.issue.pull_request && github.event.comment.body == 'DEPLOY STAGING')
    permissions:
      id-token: write
      contents: write # This is required for actions/checkout@v3
      pull-requests: write # This is required for PR commenting

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/592763168884/locations/global/workloadIdentityPools/goflink-github-actions/providers/github-actions
          service_account: ${{ fromJson(needs.params.outputs.params).service_account }}

      - name: Log gcloud configuration
        run: |-
          gcloud info

      - id: get-gke-credentials
        name: get GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          project_id: flink-core-shared
          location: europe-west3
          cluster_name: k8s-main-shared

      - name: Create short sha of current checked out commit
        run: echo "LOCAL_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV


      - uses: actions/github-script@v6
        id: pr-latest-commit-sha
        name: Get PRs latest commit SHA
        with:
          script: |
            if (context.eventName === "workflow_dispatch") {
              if ("${{ github.event.inputs.tag }}" === "") {
                return "${{ env.LOCAL_SHORT_SHA }}";
              }
              return "${{ github.event.inputs.tag }}";
            }
            const result = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return result.data.head.sha.slice(0, 7);
          result-encoding: string

      - name: Trigger workload deployment
        uses: goflink/github-actions/trigger-workload-deployment@v1
        with:
          gcp_access_token: ${{ steps.auth.outputs.access_token }}
          environment: staging
          image_tag: ${{ steps.pr-latest-commit-sha.outputs.result }}
          image_url: ${{ fromJson(needs.params.outputs.params).image_repository_reference }}
          tag_path: ".workload.image.tag"
          pr_notification_enabled: "true"
